create table if not exists public.user_api_keys (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  service text not null default 'io_net',
  api_key text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint user_api_keys_service_check check (service in ('io_net')),
  constraint user_api_keys_api_key_check check (char_length(trim(api_key)) >= 20),
  constraint user_api_keys_user_service_unique unique (user_id, service)
);

create index if not exists user_api_keys_user_id_idx
  on public.user_api_keys (user_id);

create or replace function public.set_user_api_keys_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_user_api_keys_updated_at on public.user_api_keys;

create trigger trg_user_api_keys_updated_at
before update on public.user_api_keys
for each row
execute function public.set_user_api_keys_updated_at();

alter table public.user_api_keys enable row level security;

drop policy if exists "user_api_keys_select_own" on public.user_api_keys;
create policy "user_api_keys_select_own"
on public.user_api_keys
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_api_keys_insert_own" on public.user_api_keys;
create policy "user_api_keys_insert_own"
on public.user_api_keys
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_api_keys_update_own" on public.user_api_keys;
create policy "user_api_keys_update_own"
on public.user_api_keys
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_api_keys_delete_own" on public.user_api_keys;
create policy "user_api_keys_delete_own"
on public.user_api_keys
for delete
to authenticated
using (auth.uid() = user_id);
